Repository rokibulislaam/Wordpress.com_lowdb, pull requests merged in 2020-10, with the labels that each got.

#2 Create a command line guided "settings initialization" suite, add README
  README.md
  initSettings.js
  lib/fileHandlers.js
  package.json
  settings.js
  utils/makeID.js
  wp_com_settings.json
Labels: documentation, hacktoberfest-accepted

#3 Fix and improve documentations & Add CODE_OF_CONDUCT
  CODE_OF_CONDUCT.md
  README.md
Labels: documentation, hacktoberfest-accepted

#4 Enhancement: Add a few more options in initSettings.js, add lib/parseWPImagePath.js
  initSettings.js
  lib/parseWPImagePath.js
Labels: enhancement

#6 Add wordpress "srcset" URL parser in lib/parseWPSrcsetURL.js
  lib/parseWPImagePath.js
  lib/parseWPSrcsetURL.js
Labels: enhancement, hacktoberfest-accepted

#7 Add HTML parser
  lib/htmlParser.js
  settings.js
Labels: hacktoberfest-accepted
